module.exports = {
    'Country/Region': 'Region',
    'Province/State': 'Province',
    'symptom': 'Symptoms',
    'death': 'IsDead',
    'from Wuhan': 'FromWuhan',
    'visiting Wuhan': 'VisitedWuhan',
    'exposure_end': 'ExposureEnd',
    'exposure_start': 'ExposureStart',
    'hosp_visit_date': 'HospitalVisitDate',
    'If_onset_approximated': 'IsOnsetApproximated',
    'reporting date': 'ReportingDate',
    'case_in_country': 'CaseInCountry',
    'symptom_onset': 'SymptomOnset',
    'geo_resolution': 'GeoResolution',
    'date_onset_symptoms': 'DateOnsetSymptom',
    'date_admission_hospital': 'HospitalAdmissionDate',
    'date_confirmation': 'ConfirmationDate',
    'lives_in_Wuhan': 'LivesInWuhan',
    'travel_history_dates': 'TravelHistoryDates',
    'travel_history_location': 'TravelHistoryLocation',
    'reported_market_exposure': 'ReportedMarketExposure',
    'additional_information': 'AdditionalInformation',
    'chronic_disease_binary': 'ChronicDiseaseBinary',
    'chronic_disease': 'ChronicDisease',
    'sequence_available': 'SequenceAvailable',
    'date_death_or_discharge': 'DateDeathOrDischarge',
    'notes_for_discussion': 'NotesForDiscussion',
    'country_new': 'NewCountry',
    'admin_id': 'AdminId',
    'data_moderator_initials': 'DataModeratorInitials',
    'Last Update': 'LastUpdate'
};