export default {
    login: 'Log in',
    register: 'Register',
    username: 'Username',
    password: 'Password',
    repeatPassword: 'Repeat Password',
    uploadCSV: 'Upload CSV',
    import: 'Import',
    importType: 'Import Type',
    file: 'File',
    dataImport: 'Data Import',
    dataRegions: 'Current Data',
    region: 'Region',
    province: 'Province',
    logout: 'Logout',
    provinces: 'Provinces',
    dataProvinces: 'Past Data',
    details: 'Details',
    caseUpdates: 'Case Updates',
    yes: 'yes',
    no: 'no',
}